#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

sudo apt install light udev -y

sudo cp "$SCRIPT_DIR/bin/power_events" /usr/local/bin/
sudo cp "$SCRIPT_DIR/bin/99-power-events.rules" /etc/udev/rules.d/ && sudo udevadm control --reload-rules

echo "Installation complete"
